import os
from datetime import datetime
from typing import Any, Dict, List, Optional, Type
from uuid import uuid4

from ..domain.models import DetectionResult, EvidenceBundle, RiskSummary
from ..modules.ai_detector import AIDetector
from ..modules.metadata_extractor import MetadataExtractor
from ..modules.pixel_analyzer import PixelAnalyzer
from ..modules.steg_detector import StegDetector


class AnalysisService:
    SUPPORTED_MODES = {"all", "ai", "metadata", "pixel", "steg"}
    AI_METADATA_VALUE_TERMS = (
        "midjourney",
        "stable diffusion",
        "stability ai",
        "stabilityai",
        "automatic1111",
        "comfyui",
        "fooocus",
        "invokeai",
        "dreamstudio",
        "dall-e",
        "dalle",
        "firefly",
        "flux",
        "sdxl",
        "novelai",
        "generative fill",
        "generated by ai",
        "ai generated",
    )
    AI_METADATA_KEY_TERMS = (
        "prompt",
        "negative prompt",
        "model",
        "sampler",
        "steps",
        "seed",
        "cfg scale",
        "workflow",
        "generation",
        "source",
    )
    CAMERA_POSITIVE_TERMS = (
        "canon",
        "nikon",
        "sony",
        "fujifilm",
        "panasonic",
        "leica",
        "hasselblad",
        "iphone",
        "huawei",
        "xiaomi",
        "oppo",
        "vivo",
        "directly photographed",
        "digital camera",
        "lens",
        "lightroom",
        "camera raw",
    )

    def __init__(
        self,
        metadata_extractor_factory: Type[MetadataExtractor] = MetadataExtractor,
        ai_detector_factory: Type[AIDetector] = AIDetector,
        pixel_analyzer_factory: Type[PixelAnalyzer] = PixelAnalyzer,
        steg_detector_factory: Type[StegDetector] = StegDetector,
        ml_model_path: str | None = None,
    ):
        self.metadata_extractor_factory = metadata_extractor_factory
        self.ai_detector_factory = ai_detector_factory
        self.pixel_analyzer_factory = pixel_analyzer_factory
        self.steg_detector_factory = steg_detector_factory
        self.ml_model_path = ml_model_path
        self._ml_classifier = None

    def analyze(self, image_path: str, mode: str, filename: Optional[str] = None) -> Dict[str, Any]:
        result = self.analyze_domain(image_path, mode, filename)
        return result.evidence.to_dict() | {
            "filename": result.filename,
            "mode": result.mode,
            "risk": {
                "level": result.risk.level,
                "ai_probability": result.risk.ai_probability,
                "confidence": result.risk.confidence,
                "summary": result.risk.summary,
                "score": result.risk.score,
                "evidence_summary": result.risk.evidence_summary,
                "explanation": result.risk.explanation,
            },
        }

    def analyze_domain(self, image_path: str, mode: str, filename: Optional[str] = None) -> DetectionResult:
        normalized_mode = (mode or "all").lower()
        if normalized_mode not in self.SUPPORTED_MODES:
            raise ValueError("Unsupported analyze mode")

        metadata = None
        ai_detection = None
        pixel_analysis = None
        steg_detection = None

        if normalized_mode in {"all", "metadata", "ai"}:
            metadata = self.metadata_extractor_factory().extract_all_metadata(image_path)

        if normalized_mode in {"all", "pixel"}:
            pixel_analysis = self.pixel_analyzer_factory().analyze_all(image_path)

        if normalized_mode in {"all", "ai"}:
            metadata_indicators = self._collect_metadata_indicators(metadata or {})
            ai_context = self._build_ai_context(metadata or {}, pixel_analysis if normalized_mode in {"all", "pixel"} else None)
            ai_context["has_strong_ai_metadata"] = bool(metadata_indicators)
            ai_context["has_camera_markers"] = self._analyze_metadata_signals(metadata or {}, metadata_indicators).get("has_camera_markers", False)
            ai_detection = self._run_ai_detection(image_path, metadata_indicators, ai_context)

        if normalized_mode in {"all", "steg"}:
            steg_detection = self.steg_detector_factory().analyze_all(image_path)

        evidence = EvidenceBundle(
            ai_detection=ai_detection,
            metadata=metadata if normalized_mode in {"all", "metadata"} else None,
            pixel_analysis=pixel_analysis,
            steg_detection=steg_detection,
        )

        risk = self._build_risk_summary(
            ai_detection,
            metadata=metadata if normalized_mode in {"all", "metadata", "ai"} else None,
            pixel_analysis=pixel_analysis,
            steg_detection=steg_detection,
        )

        return DetectionResult(
            task_id=str(uuid4()),
            filename=filename or image_path,
            mode=normalized_mode,
            created_at=datetime.utcnow().isoformat(),
            risk=risk,
            evidence=evidence,
        )

    def _build_risk_summary(self, ai_detection: Optional[Dict[str, Any]]) -> RiskSummary:
        if not ai_detection:
            return RiskSummary(level="unknown", ai_probability=0.0, confidence=0.0, summary="当前模式未生成 AI 风险结论", score=0.0, evidence_summary=["当前模式未执行 AI 风险计算"])

        probability = float(ai_detection.get("ai_probability", 0.0))
        confidence = float(ai_detection.get("confidence", 0.0))
        score = round(probability * 100, 2)
        if probability >= 0.75:
            level = "high"
        elif probability >= 0.4:
            level = "medium"
        else:
            level = "low"

        summary = f"AI 概率 {probability:.2%}，置信度 {confidence:.2%}"
        evidence_summary = [
            f"AI概率 {probability:.2%}",
            f"置信度 {confidence:.2%}",
        ]
        return RiskSummary(
            level=level,
            ai_probability=probability,
            confidence=confidence,
            summary=summary,
            score=score,
            evidence_summary=evidence_summary,
        )

    def _collect_metadata_indicators(self, metadata: Dict[str, Any]) -> List[str]:
        indicators: List[str] = []
        exif = metadata.get("exif", {})
        png_chunks = metadata.get("png_chunks", {})

        for key, value in exif.items():
            normalized_key = str(key).lower()
            normalized_value = str(value).lower()
            if any(term in normalized_value for term in self.AI_METADATA_VALUE_TERMS):
                indicators.append(f"EXIF生成元数据: {key}")
                continue
            if any(term in normalized_key for term in self.AI_METADATA_KEY_TERMS) and any(term in normalized_value for term in self.AI_METADATA_VALUE_TERMS):
                indicators.append(f"EXIF生成参数: {key}")

        text_chunk = png_chunks.get("tEXt")
        if isinstance(text_chunk, dict):
            keyword = text_chunk.get("keyword", "").lower()
            text = text_chunk.get("text", "").lower()
            if any(term in keyword for term in self.AI_METADATA_KEY_TERMS) and any(term in text for term in self.AI_METADATA_VALUE_TERMS):
                indicators.append(f"PNG生成参数: {keyword}")
            elif any(term in text for term in self.AI_METADATA_VALUE_TERMS):
                indicators.append("PNG文本包含生成器标识")

        return indicators

    def _run_ai_detection(self, image_path: str, metadata_indicators: List[str], ai_context: Dict[str, Any]) -> Dict[str, Any]:
        detector = self.ai_detector_factory()
        try:
            result = detector.detect(image_path, metadata_indicators, ai_context)
        except TypeError:
            result = detector.detect(image_path, metadata_indicators)

        if self.ml_model_path and os.path.exists(self.ml_model_path):
            if self._ml_classifier is None:
                from ..modules.ml_classifier import MLClassifier

                self._ml_classifier = MLClassifier(self.ml_model_path)
            if self._ml_classifier is not None and self._ml_classifier.is_available():
                width = int(ai_context.get("width", 0) or 0)
                height = int(ai_context.get("height", 0) or 0)
                normalized_features = result.get("normalized_features", {}) or {}
                ml_probability = float(self._ml_classifier.predict_probability(normalized_features, width, height))
                result = dict(result)
                result["ai_probability_raw"] = float(result.get("ai_probability", 0.0) or 0.0)
                result["ai_probability"] = ml_probability
                result["ml_applied"] = True
                result["ml_model_path"] = self.ml_model_path
                result["is_likely_ai"] = ml_probability > 0.6
        return result

    def _build_ai_context(self, metadata: Dict[str, Any], pixel_analysis: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        image_info = metadata.get("image_info", {})
        pixel_patterns = (pixel_analysis or {}).get("pixel_patterns", {})
        correlations = pixel_patterns.get("color_correlation", {})
        avg_correlation = 0.0
        if correlations:
            avg_correlation = sum(float(v) for v in correlations.values()) / len(correlations)
        mean_entropy = float((pixel_analysis or {}).get("entropy", {}).get("mean_entropy", 0.0) or 0.0)
        color_diversity = float(pixel_patterns.get("color_diversity", 0.0) or 0.0)
        noise_ratio = float((pixel_analysis or {}).get("noise_analysis", {}).get("noise_ratio", 0.0) or 0.0)
        is_document_like = mean_entropy < 2.0 and color_diversity < 0.001 and avg_correlation > 0.98

        return {
            "width": int(image_info.get("width", 0) or 0),
            "height": int(image_info.get("height", 0) or 0),
            "mean_entropy": mean_entropy,
            "color_diversity": color_diversity,
            "avg_correlation": avg_correlation,
            "noise_ratio": noise_ratio,
            "is_document_like": is_document_like,
            "has_camera_markers": False,
            "has_strong_ai_metadata": False,
        }

    def _build_risk_summary(
        self,
        ai_detection: Optional[Dict[str, Any]],
        metadata: Optional[Dict[str, Any]] = None,
        pixel_analysis: Optional[Dict[str, Any]] = None,
        steg_detection: Optional[Dict[str, Any]] = None,
    ) -> RiskSummary:
        if not ai_detection:
            return RiskSummary(level="unknown", ai_probability=0.0, confidence=0.0, summary="当前模式未生成 AI 风险结论", score=0.0, evidence_summary=["当前模式未执行 AI 风险计算"])

        metadata_signals = self._analyze_metadata_signals(metadata or {}, ai_detection.get("metadata_indicators", []))
        visual_signals = self._analyze_visual_signals(ai_detection, pixel_analysis or {}, metadata or {})
        watermark_signals = self._analyze_watermark_signals(steg_detection or {})

        ai_probability = float(ai_detection.get("ai_probability", 0.0))
        confidence = float(ai_detection.get("confidence", 0.0))

        # 大幅提高AI风险概率权重，让AI概率直接成为主要依据
        ai_weighted = ai_probability * 100.0 * 0.6  # AI概率占60%权重（0-60分）
        metadata_weighted = metadata_signals["score"] * 0.25  # 元数据占25%
        visual_weighted = visual_signals["score"] * 0.1  # 视觉信号占10%
        watermark_weighted = watermark_signals["score"] * 0.05  # 隐写占5%
        
        weighted_score = ai_weighted + metadata_weighted + visual_weighted + watermark_weighted
        weighted_score += min(max((confidence - 0.5) * 8, -3), 3)

        if metadata_signals["has_strong_ai_metadata"]:
            weighted_score = max(weighted_score, 82.0)

        if visual_signals["is_document_like"] and not metadata_signals["has_strong_ai_metadata"]:
            weighted_score = min(weighted_score, 22.0)

        if metadata_signals["has_camera_markers"] and not metadata_signals["has_strong_ai_metadata"]:
            weighted_score = min(weighted_score, 58.0)

        has_counter_evidence = visual_signals["is_document_like"] or metadata_signals["has_camera_markers"]
        
        # 调整最小分数，确保AI概率在50%以上时至少能到中等风险（当没有反证时）
        if ai_probability >= 0.50 and confidence >= 0.5 and not has_counter_evidence:
            weighted_score = max(weighted_score, 45.0)
        if ai_probability >= 0.60 and confidence >= 0.55 and not has_counter_evidence:
            weighted_score = max(weighted_score, 52.0)
        if ai_probability >= 0.75 and confidence >= 0.65 and not has_counter_evidence:
            weighted_score = max(weighted_score, 65.0)
        if ai_probability >= 0.85 and confidence >= 0.7 and not has_counter_evidence:
            weighted_score = max(weighted_score, 78.0)

        score = round(min(max(weighted_score, 0.0), 100.0), 2)

        if metadata_signals["has_strong_ai_metadata"]:
            level = "high"
        elif ai_probability >= 0.80 and score >= 70 and confidence >= 0.65 and not visual_signals.get("is_screenshot_like", False):
            level = "high"
        elif score >= 45:
            level = "medium"
        elif score > 0:
            level = "low"
        else:
            level = "unknown"

        evidence_summary = metadata_signals["evidence"] + visual_signals["evidence"] + watermark_signals["evidence"]
        if not evidence_summary:
            evidence_summary = [f"视觉模型分数 {ai_probability:.2%}"]

        summary_parts = [f"综合风险分 {score:.2f}"]
        if metadata_signals["has_strong_ai_metadata"]:
            summary_parts.append("存在明确生成元数据")
        elif visual_signals["is_document_like"]:
            summary_parts.append("更接近文档/流程图，不作为高风险依据")
        else:
            summary_parts.append(f"视觉模型分数 {ai_probability:.2%}")

        return RiskSummary(
            level=level,
            ai_probability=ai_probability,
            confidence=confidence,
            summary="，".join(summary_parts),
            score=score,
            evidence_summary=evidence_summary[:6],
            explanation=self._build_risk_explanation(level, metadata_signals, visual_signals, watermark_signals, evidence_summary[:6]),
        )

    def _build_risk_explanation(
        self,
        level: str,
        metadata_signals: Dict[str, Any],
        visual_signals: Dict[str, Any],
        watermark_signals: Dict[str, Any],
        evidence_summary: List[str],
    ) -> Dict[str, Any]:
        level_label_map = {
            "high": "高风险",
            "medium": "中风险",
            "low": "低风险",
            "unknown": "结果不足",
        }
        level_desc_map = {
            "high": "检测到较强可疑信号，建议优先人工复核来源与生成链路。",
            "medium": "存在部分可疑信号，但还不足以单独作为定性结论。",
            "low": "当前未发现足够强的 AI 生成证据，结果更适合作为低风险提示。",
            "unknown": "当前证据不足，暂时无法给出稳定结论。",
        }

        if metadata_signals.get("has_strong_ai_metadata"):
            primary_reason = "检测到明确生成器元数据或生成参数，这是当前最强证据。"
        elif visual_signals.get("is_document_like"):
            primary_reason = "图像更接近文档、流程图或截图形态，因此对视觉高分做了降权处理。"
        elif metadata_signals.get("has_camera_markers"):
            primary_reason = "存在相机或拍摄链路元数据，因此未将视觉异常直接上调为高风险。"
        elif evidence_summary:
            primary_reason = evidence_summary[0]
        else:
            primary_reason = "当前缺少足够稳定的高置信证据。"

        if level == "high":
            action = "建议结合原始文件、来源平台、导出记录和更多样本做人工复核。"
        elif level == "medium":
            action = "建议补充原图来源、拍摄链路或更多相邻样本再判断。"
        elif level == "low":
            action = "建议保留原图与来源信息，如业务敏感仍可人工抽检。"
        else:
            action = "建议补充更多证据后再次检测，例如原图、元数据完整文件或来源说明。"

        evidence_groups = [
            {"title": "元数据证据", "items": metadata_signals.get("evidence", []) or ["未发现明确生成器标识"]},
            {"title": "视觉证据", "items": visual_signals.get("evidence", []) or ["未提取到稳定视觉证据"]},
            {"title": "水印与隐写", "items": watermark_signals.get("evidence", []) or ["未发现足以单独定性的水印证据"]},
        ]

        image_classification_tags: List[str] = []
        if visual_signals.get("is_document_like"):
            image_classification_tags.append("文档/流程图")
        if metadata_signals.get("has_camera_markers"):
            image_classification_tags.append("相机链路")
        if metadata_signals.get("has_strong_ai_metadata"):
            image_classification_tags.append("生成元数据")
        if not image_classification_tags:
            image_classification_tags.append("待进一步判别")

        return {
            "level_label": level_label_map.get(level, "结果不足"),
            "probability_label": "AI风险概率",
            "probability_description": "该数值是启发式模型评分，不等同于真实后验概率，应结合元数据、视觉证据和来源信息一起理解。",
            "image_classification_tags": image_classification_tags,
            "level_description": level_desc_map.get(level, "当前证据不足。"),
            "primary_reason": primary_reason,
            "action": action,
            "evidence_groups": evidence_groups,
        }

    def _analyze_metadata_signals(self, metadata: Dict[str, Any], indicators: List[str]) -> Dict[str, Any]:
        exif = metadata.get("exif", {})
        image_info = metadata.get("image_info", {})
        png_chunks = metadata.get("png_chunks", {})
        score = 0.0
        evidence: List[str] = []

        has_strong_ai_metadata = len(indicators) > 0
        if has_strong_ai_metadata:
            score += 90.0
            evidence.append(f"元数据命中 {len(indicators)} 条生成器线索")

        software_text = " ".join(str(value).lower() for key, value in exif.items() if "software" in str(key).lower())
        if any(term in software_text for term in self.AI_METADATA_VALUE_TERMS):
            score = max(score, 95.0)
            has_strong_ai_metadata = True
            evidence.append("软件标记包含生成器名称")

        png_text = " ".join(str(value).lower() for value in png_chunks.values())
        if any(term in png_text for term in self.AI_METADATA_VALUE_TERMS):
            score = max(score, 90.0)
            has_strong_ai_metadata = True
            evidence.append("PNG文本包含生成参数或生成器标识")

        combined_camera_text = " ".join([str(v).lower() for v in exif.values()]) + " " + str(image_info.get("mode", "")).lower()
        has_camera_markers = any(term in combined_camera_text for term in self.CAMERA_POSITIVE_TERMS)
        if has_camera_markers and not has_strong_ai_metadata:
            score = max(score - 20.0, 0.0)
            evidence.append("存在相机/拍摄链路元数据")

        return {
            "score": min(max(score, 0.0), 100.0),
            "evidence": evidence,
            "has_strong_ai_metadata": has_strong_ai_metadata,
            "has_camera_markers": has_camera_markers,
        }

    def _analyze_visual_signals(self, ai_detection: Dict[str, Any], pixel_analysis: Dict[str, Any], metadata: Dict[str, Any]) -> Dict[str, Any]:
        features = ai_detection.get("features", {})
        normalized = ai_detection.get("normalized_features", {})
        entropy = float(pixel_analysis.get("entropy", {}).get("mean_entropy", features.get("color_entropy", 0.0)) or 0.0)
        pixel_patterns = pixel_analysis.get("pixel_patterns", {})
        color_diversity = float(pixel_patterns.get("color_diversity", 0.0) or 0.0)
        correlations = pixel_patterns.get("color_correlation", {})
        avg_corr = 0.0
        if correlations:
            avg_corr = sum(float(v) for v in correlations.values()) / len(correlations)
        noise_ratio = float(pixel_analysis.get("noise_analysis", {}).get("noise_ratio", 0.0) or 0.0)
        width = int(metadata.get("image_info", {}).get("width", 0) or 0)
        height = int(metadata.get("image_info", {}).get("height", 0) or 0)
        aspect_ratio = width / height if width and height else 1.0
        exif = metadata.get("exif", {}) or {}
        exif_present = isinstance(exif, dict) and len(exif) > 0
        common_screenshot_widths = {720, 1080, 1125, 1170, 1242, 1284, 1440, 1536}
        is_screenshot_like = (
            (not exif_present)
            and width > 0
            and height > 0
            and (max(width, height) / max(min(width, height), 1)) >= 1.55
            and (width in common_screenshot_widths or height in common_screenshot_widths or max(width, height) <= 5000)
        )

        score = float(ai_detection.get("ai_probability", 0.0)) * 100.0
        evidence = [f"视觉模型分数 {float(ai_detection.get('ai_probability', 0.0)):.2%}"]

        is_document_like = (
            entropy < 2.0
            and color_diversity < 0.001
            and avg_corr > 0.98
        )
        if is_document_like:
            score = min(score, 18.0)
            evidence.append("图像更像文档/流程图/截图")
        elif is_screenshot_like:
            score = min(score, 62.0)
            evidence.append("图像更像手机截图，降低高风险判定")

        if normalized.get("texture_score", 0.0) and normalized.get("edge_quality", 0.0) and entropy > 5.5 and color_diversity > 0.01:
            score += 10.0
            evidence.append("自然纹理与边缘复杂度较高")

        if noise_ratio < 0.1 and avg_corr > 0.85 and 0.8 < aspect_ratio < 2.5 and not is_document_like:
            score -= 8.0
            evidence.append("画面噪声与色彩相关性更接近相机照片")

        if float(features.get("metadata_score", 0.0) or 0.0) > 0:
            score += 5.0

        return {
            "score": min(max(score, 0.0), 100.0),
            "evidence": evidence,
            "is_document_like": is_document_like,
            "is_screenshot_like": is_screenshot_like,
        }

    def _analyze_watermark_signals(self, steg_detection: Dict[str, Any]) -> Dict[str, Any]:
        if not steg_detection:
            return {"score": 0.0, "evidence": []}

        overall_confidence = float(steg_detection.get("overall_confidence", 0.0) or 0.0)
        suspicious_tests = int(steg_detection.get("total_suspicious_tests", 0) or 0)

        if suspicious_tests >= 3 and overall_confidence > 0.75:
            return {"score": 35.0, "evidence": ["存在较强隐写/水印异常，需人工复核"]}
        if suspicious_tests >= 2 and overall_confidence > 0.5:
            return {"score": 18.0, "evidence": ["存在轻度隐写异常，但不能直接等同 AI 水印"]}
        return {"score": 5.0 if overall_confidence > 0.4 else 0.0, "evidence": []}
