import json
import os
from typing import Any, Dict


class ExportService:
    def __init__(self, export_folder: str):
        self.export_folder = export_folder
        os.makedirs(self.export_folder, exist_ok=True)

    def export(self, filename: str, format_type: str, result: Dict[str, Any]) -> Dict[str, str]:
        normalized_format = (format_type or "md").lower()
        export_filename = f"{filename}.{normalized_format}"
        export_path = os.path.join(self.export_folder, export_filename)

        if normalized_format == "md":
            content = self.generate_markdown(result)
        elif normalized_format == "txt":
            content = self.generate_text(result)
        elif normalized_format == "json":
            content = json.dumps(result, indent=2, ensure_ascii=False)
        else:
            raise ValueError("Unsupported format")

        with open(export_path, "w", encoding="utf-8") as file:
            file.write(content)

        return {
            "path": export_path,
            "filename": export_filename,
            "format": normalized_format,
            "download_url": f"/api/export/download/{export_filename}",
        }

    def generate_markdown(self, result: Dict[str, Any]) -> str:
        content = "# AI Image Detection Report\n\n"
        content += f"## File: {result.get('filename', 'Unknown')}\n\n"

        risk = result.get('risk', {})
        explanation = risk.get('explanation', {})
        if risk:
            content += "## Risk Summary\n\n"
            content += f"- Level: {risk.get('level', 'unknown')}\n"
            content += f"- Summary: {risk.get('summary', 'N/A')}\n"
            if explanation:
                content += f"- 风险等级说明: {explanation.get('level_label', 'N/A')}\n"
                content += f"- 等级解释: {explanation.get('level_description', 'N/A')}\n"
                content += f"- 主要原因: {explanation.get('primary_reason', 'N/A')}\n"
                content += f"- 建议动作: {explanation.get('action', 'N/A')}\n"
                content += "\n### Evidence Groups\n\n"
                for group in explanation.get('evidence_groups', []):
                    content += f"#### {group.get('title', 'Evidence')}\n"
                    for item in group.get('items', []):
                        content += f"- {item}\n"
                    content += "\n"

        if "metadata" in result:
            metadata = result["metadata"]
            image_info = metadata.get("image_info", {})
            content += "## Metadata\n\n"
            content += f"- File Size: {metadata.get('file_size', 'N/A')} bytes\n"
            content += f"- Format: {image_info.get('format', 'N/A')}\n"
            content += f"- Dimensions: {image_info.get('width', 'N/A')}x{image_info.get('height', 'N/A')}\n"
            content += f"- Mode: {image_info.get('mode', 'N/A')}\n"

        if "ai_detection" in result:
            detection = result["ai_detection"]
            content += "\n## AI Generation Detection\n\n"
            content += f"- AI Probability: {detection.get('ai_probability', 0):.2%}\n"
            content += f"- Confidence: {detection.get('confidence', 0):.2%}\n"
            content += f"- Likely AI Generated: {'Yes' if detection.get('is_likely_ai') else 'No'}\n"

        if "pixel_analysis" in result:
            pixel = result["pixel_analysis"]
            content += "\n## Pixel Analysis\n\n"
            content += f"- Color Diversity: {pixel.get('pixel_patterns', {}).get('color_diversity', 0):.4f}\n"
            content += f"- Mean Entropy: {pixel.get('entropy', {}).get('mean_entropy', 0):.2f}\n"

        if "steg_detection" in result:
            steg = result["steg_detection"]
            content += "\n## Steganography Detection\n\n"
            content += f"- Suspicious Tests: {steg.get('total_suspicious_tests', 0)}/4\n"
            content += f"- Overall Confidence: {steg.get('overall_confidence', 0):.2%}\n"

        content += "\n---\nGenerated by AI Image Detection Toolkit\n"
        return content

    def generate_text(self, result: Dict[str, Any]) -> str:
        content = "=" * 60 + "\n"
        content += "AI Image Detection Report\n"
        content += "=" * 60 + "\n\n"
        content += f"File: {result.get('filename', 'Unknown')}\n\n"

        risk = result.get('risk', {})
        explanation = risk.get('explanation', {})
        if risk:
            content += "[Risk Summary]\n"
            content += "-" * 60 + "\n"
            content += f"  Level: {risk.get('level', 'unknown')}\n"
            content += f"  Summary: {risk.get('summary', 'N/A')}\n"
            if explanation:
                content += f"  风险等级说明: {explanation.get('level_label', 'N/A')}\n"
                content += f"  等级解释: {explanation.get('level_description', 'N/A')}\n"
                content += f"  主要原因: {explanation.get('primary_reason', 'N/A')}\n"
                content += f"  建议动作: {explanation.get('action', 'N/A')}\n"
                for group in explanation.get('evidence_groups', []):
                    content += f"  {group.get('title', 'Evidence')}:\n"
                    for item in group.get('items', []):
                        content += f"    - {item}\n"
            content += "\n"

        if "metadata" in result:
            metadata = result["metadata"]
            image_info = metadata.get("image_info", {})
            content += "[Metadata]\n"
            content += "-" * 60 + "\n"
            content += f"  File Size: {metadata.get('file_size', 'N/A')} bytes\n"
            content += f"  Format: {image_info.get('format', 'N/A')}\n"
            content += f"  Dimensions: {image_info.get('width', 'N/A')}x{image_info.get('height', 'N/A')}\n"
            content += f"  Mode: {image_info.get('mode', 'N/A')}\n\n"

        if "ai_detection" in result:
            detection = result["ai_detection"]
            content += "[AI Generation Detection]\n"
            content += "-" * 60 + "\n"
            content += f"  AI Probability: {detection.get('ai_probability', 0):.2%}\n"
            content += f"  Confidence: {detection.get('confidence', 0):.2%}\n"
            content += f"  Likely AI Generated: {'Yes' if detection.get('is_likely_ai') else 'No'}\n\n"

        if "pixel_analysis" in result:
            pixel = result["pixel_analysis"]
            content += "[Pixel Analysis]\n"
            content += "-" * 60 + "\n"
            content += f"  Color Diversity: {pixel.get('pixel_patterns', {}).get('color_diversity', 0):.4f}\n"
            content += f"  Mean Entropy: {pixel.get('entropy', {}).get('mean_entropy', 0):.2f}\n\n"

        if "steg_detection" in result:
            steg = result["steg_detection"]
            content += "[Steganography Detection]\n"
            content += "-" * 60 + "\n"
            content += f"  Suspicious Tests: {steg.get('total_suspicious_tests', 0)}/4\n"
            content += f"  Overall Confidence: {steg.get('overall_confidence', 0):.2%}\n\n"

        content += "=" * 60 + "\n"
        content += "Generated by AI Image Detection Toolkit\n"
        return content
